"""
Django settings for lga_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pv-3x)f3yux-3ibvucovpc8etf52k#$pel+!o%3#m%@3iw(u^c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1',
                'la-grande-aventure.com','la-grande-aventure.fr',
                 'https://www.la-grande-aventure.com',
                 'https://la-grande-aventure.com',
                 'https://www.la-grande-aventure.fr',
                 'https://la-grande-aventure.fr',
                 'http://www.la-grande-aventure.com',
                 'http://la-grande-aventure.com',
                 'http://www.la-grande-aventure.fr',
                 'http://la-grande-aventure.fr',
                 'https://grandeaventure-production.up.railway.app',
                 'https://www.grandeaventure-production.up.railway.app',
                 'http://grandeaventure-production.up.railway.app',
                'http://www.grandeaventure-production.up.railway.app',
                    'grandeaventure-production.up.railway.app'
                 ]

CSRF_TRUSTED_ORIGINS = ['https://lagrandeaventure.fr','https://www.lagrandeaventure.fr',
                        'https://www.la-grande-aventure.com',
                        'https://la-grande-aventure.com',
                        'https://www.la-grande-aventure.fr',
                        'https://la-grande-aventure.fr',
                        'https://grandeaventure-production.up.railway.app/'
                        ]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lga_app',
    'whitenoise.runserver_nostatic',
    # 'embed_video',
    # 'django.contrib.postgres',
    # 'django_ckeditor_5',
    # 'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'lga_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lga_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


CURRENT_FLAG = 1

if CURRENT_FLAG == 0:
    CURRENT_ENV = "dev"
elif CURRENT_FLAG == 1:
    CURRENT_ENV = "prod"
if CURRENT_ENV == "dev":
    if True:
        DATABASES = {
            'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'GRANDE_AVENTURE_DEV_DB',
                        'USER': 'postgres', 'PASSWORD': 'açjdzzalêzaA129',
                        'HOST': 'localhost', 'PORT': '5432', },
        }
    else:
        DATABASES = {
                'default': {        'ENGINE': 'django.db.backends.sqlite3',
                                    'NAME': BASE_DIR / 'db.sqlite3',}
                }
if CURRENT_ENV == "prod":
    DATABASES = {
             'default': {'ENGINE': 'django.db.backends.postgresql','NAME': 'railway','USER': 'postgres','PASSWORD': 'eKowMwXgKKzLxhJPgqqgYtnGxpMoyBzI','HOST': 'nozomi.proxy.rlwy.net','PORT': '38815',  },
    }

REDIRECT_URI_BASE = "https://lagrandeaventure.fr"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = ['static/']

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
